program = { SOI ~ function ~ EOI }
function = { type_specifier ~ identifier ~ "(" ~ ")" ~ "{" ~ statement+ ~ "}" }
statement = _{ return_statement }
return_statement = ${ "return" ~ WHITESPACE+ ~ expression ~ WHITESPACE* ~ ";" }
expression = _{ integer }
identifier = { (ASCII_ALPHANUMERIC | "_")+ }
type_specifier = { "int" }
integer = { ASCII_DIGIT+ }

WHITESPACE = _{ " " | "\t" | "\n" }
COMMENT = _{ "/*" ~ (!"*/" ~ ANY)* ~ "*/" }
